### ISSUE TITLE
erro initialize slashcommands

### ISSUE THREAD

**Issue by marcosmolinamaxicon** [RocketChat/Rocket.Chat.Apps-cli#47]
error on log rocketchat ao initializae slachcommands.

`[
  "{\"stack\":\"TypeError: Cannot read property 'toLowerCase' of undefined
    at AppSlashCommandManager.addCommand (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/managers/AppSlashCommandManager.js:82:43)
    at SlashCommandsExtend.provideSlashCommand (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/accessors/SlashCommandsExtend.js:9:45)
    at ManualApp.extendConfiguration (evalmachine.<anonymous>:10:37)
    at ManualApp.<anonymous> (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/definition/App.js:112:24)
    at Generator.next (<anonymous>)
    at /home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/definition/App.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/definition/App.js:3:12)
    at ManualApp.initialize (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/definition/App.js:111:16)
    at evalmachine.<anonymous>:1:-46
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at ProxiedApp.runInContext (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/ProxiedApp.js:54:19)
    at ProxiedApp.<anonymous> (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/ProxiedApp.js:72:38)
    at Generator.next (<anonymous>)
    at /home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/ProxiedApp.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/ProxiedApp.js:3:12)
    at ProxiedApp.call (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/ProxiedApp.js:57:16)
    at AppManager.<anonymous> (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/AppManager.js:504:27)
    at Generator.next (<anonymous>)
    at /home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/AppManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/AppManager.js:3:12)
    at AppManager.initializeApp (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/AppManager.js:499:16)
    at AppManager.<anonymous> (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/AppManager.js:337:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/AppManager.js:4:58)
    at /home/maxicon/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Cannot read property 'toLowerCase' of undefined\"}"
]`

**Comment by graywolf336** [comment]
Closing as this is an issue with your code:

`Cannot read property 'toLowerCase' of undefined at AppSlashCommandManager.addCommand (/home/maxicon/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/managers/AppSlashCommandManager.js:82:43`

**Comment by marcosmolinamaxicon** [comment]
31/5000
The error is in the module @ rocket.chat

/node_modules/@rocket.chat

**Comment by d-gubert** [comment]
Hi @marcosmolinamaxicon 

It appears you have mistakenly used the colon operator (`:`) instead of the equals operator (`=`) when declaring the properties of your `ManualCommand` class.

So, instead of this:
```
command: 'manual';
i18nParamsExample: 'manual';
i18nDescription: 'manual';
providesPreview: false;
```

Maybe try this:

```
command = 'manual';
i18nParamsExample = 'manual';
i18nDescription = 'manual';
providesPreview = false;
```

Also please note this repo is related only to the CLI tool provided by the `@rocket.chat/apps-cli` package; this kind of problem you're facing is related to another repo https://github.com/RocketChat/Rocket.Chat.Apps-engine
