### ISSUE TITLE
Unable to deploy app with custom nameslug

### ISSUE THREAD

**Issue by zjadir** [RocketChat/Rocket.Chat.Apps-cli#66]
After creating a new app with the `rc-apps create` command. I get the following `app.json`.

```
{
    "id": "f044466e-8540-4168-aa91-4cc94a3c860c",
    "version": "0.0.1",
    "requiredApiVersion": "^1.4.0",
    "iconFile": "icon.png",
    "author": {
        "name": "Mathieu Charest",
        "homepage": "http://localhost",
        "support": "http://localhost"
    },
    "name": "Draw.io",
    "nameSlug": "drawio",
    "classFile": "DrawIoApp.ts",
    "description": "Draw.io"
}
```

Then, I simply try to deploy the default created app with the `rc-apps deploy` command and I get 

```
packaging your app... packaged!
deploying your app... !
Error: Deployment error: undefined
    at Deploy.asyncSubmitData (C:/Users/Mathieu/AppData/Roaming/npm/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:100:19)
    at async Deploy.run (C:/Users/Mathieu/AppData/Roaming/npm/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:47:9)
    at async Deploy._run (C:/Users/Mathieu/AppData/Roaming/npm/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (C:/Users/Mathieu/AppData/Roaming/npm/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (C:/Users/Mathieu/AppData/Roaming/npm/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (C:/Users/Mathieu/AppData/Roaming/npm/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:44:20)
```

The only way for me to deploy the app is changing the nameslug to an app that exists in the market. Like Appear.In.

```
{
    "id": "f044466e-8540-4168-aa91-4cc94a3c860c",
    "version": "0.0.1",
    "requiredApiVersion": "^1.4.0",
    "iconFile": "icon.png",
    "author": {
        "name": "Mathieu Charest",
        "homepage": "http://localhost",
        "support": "http://localhost"
    },
    "name": "Draw.io",
    "nameSlug": "appearin",
    "classFile": "DrawIoApp.ts",
    "description": "Draw.io"
}
```
```
packaging your app... packaged!
deploying your app... deployed!
```

**Comment by ruvenss** [comment]
Same for us

**Comment by preeesha** [comment]
Hey @graywolf336, @ruvenss, I would like to know if this issue is still there or not.
