### ISSUE TITLE
Deployment error: Debug Failure. False expression when deploy extension

### ISSUE THREAD

**Issue by huy-lv** [RocketChat/Rocket.Chat.Apps-cli#67]
Here is the package json of my extension
```
{
    "devDependencies": {
        "@rocket.chat/apps-engine": "^1.12.0",
        "@types/node": "^10.12.14",
        "tslint": "^5.10.0",
        "typescript": "^3.7.3"
    }
}
```
When i deploy app, i got the following problem. Pls help!
```
Error: Deployment error: Debug Failure. False expression.
    at Deploy.asyncSubmitData (/usr/local/lib/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:100:19)
    at async Deploy.run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:47:9)
    at async Deploy._run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:44:20)
```

**Comment by meomay503** [comment]
Seems u have imported something that's not from the app's directory. Importing some modules that's not from apps-engine/definition will cause this issue as well

**Comment by ritwizsinha** [comment]
This error happens to me when I have a folder and I try to import all the modules in the folder to a common index.ts file. Then importing anything from this index leads to this error. In the server logs I get 
``` Failed to resolve module  [folder name]```
